name: linked_list.pairsync

on:
  push:
    branches:
      - 'feat/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pairsync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::460812442604:role/65019146c8229efe0b2332b8
          aws-region: us-east-1

      - name: PairSync
        uses: pairspaces/pairsync@v1
        with:
          repository: ${{ github.repository }}
          user: ${{ github.actor_id }}
